### ISSUE TITLE
Replying to messages with /paint?

### ISSUE THREAD

**Issue by Trainmaster9977** [JamelHammoud/paint-bot#1]
Hello! I'm looking into using this for me and my partner, but I want to ask if there would be any way to add functionality that lets you reply to specific messages.

For example, doing /paint in a reply, and the bot's post replying to the same message.

Thanks!

**Comment by JamelHammoud** [comment]
So, [Discord doesn't let you use a slash command in a reply](https://support.discord.com/hc/en-us/community/posts/1500001128682-Ability-to-add-custom-slash-commands-on-reply), but instead I was able to register a context menu command for Paint. All you have to do is open a message's settings (right click/hold a message), hover over "Apps" and click "Reply with canvas". Then paint your message and click send!

I just deployed these changes, so you should be able to test for yourself!

<img width="634" alt="image" src="https://github.com/JamelHammoud/paint-bot/assets/55815579/3f77cbd6-aec6-426f-9aec-570c1ee39ab6">
<img width="424" alt="image" src="https://github.com/JamelHammoud/paint-bot/assets/55815579/8c5c7bcd-6297-425b-95e1-208c1d177052">

**Comment by Trainmaster9977** [comment]
Oh wow, thank you so much! I'll test it out soon, you work fast!!
