### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Trainmaster9977** [JamelHammoud/paint-bot#2]
Hello! (And thanks for adding the reply feature)

I just tested out the bot, works like a charm on computer. However, I then switched to my iphone on the latest version of discord to test it there.

However, it either A. did literally nothing, except blast the message to my computer, or B. when my computer was closed, it just got stuck with the bot eternally saying "sending command".

Any idea on how to fix this? Thanks!

**Comment by JamelHammoud** [comment]
@Trainmaster9977 I was able to replicate this. I just deployed some code that _should_ fix this. Let me know if it didn't work for you, and I'll reopen this issue!

**Comment by Trainmaster9977** [comment]
Sadly, it didn't work for me, and is giving the same behavior as before.

Sorry for the late responses by the way! You work faster than I can keep up with lol
